//地球半径
const EARTH_ARC = 111.199
//喷洒半径
const DISTANCE = 22.5
// const FILLCOLOR = '#f1c721'
const FILLCOLOR = '#ffffff'
const LINE_COLOR = 'red'
const LINE_WEIGHT = 2.5
const LINE_OPACITY = 0.8
const POLYGON_COLOR = FILLCOLOR
const POLYGON_WEIGHT = 1
const POLYGON_OPACITY = 0.1
const POLYGON_FILLCOLOR = FILLCOLOR
const POLYGON_FILLOPACITY = 0.3
//tri hm
const TRI_COLOR = FILLCOLOR
const TRI_WEIGHT = 1
const TRI_OPACITY = 0.1
const TRI_FILLCOLOR = FILLCOLOR
const TRI_FILLOPACITY = 0.3
const HM_FILLOPACITY = 0.3
//area
const AREA_COLOR = '#fff'
const AREA_WEIGHT = 1
const AREA_OPACITY = 0.1
const AREA_FILLCOLOR = '#fff'
const AREA_FILLOPACITY = 0.7

const common = {
    EARTH_ARC,
    //喷洒半径
    DISTANCE,
    FILLCOLOR,
    LINE_COLOR,
    LINE_WEIGHT,
    LINE_OPACITY,
    POLYGON_COLOR,
    POLYGON_WEIGHT,
    POLYGON_OPACITY,
    POLYGON_FILLCOLOR,
    POLYGON_FILLOPACITY,
    TRI_COLOR,
    TRI_WEIGHT,
    TRI_OPACITY,
    TRI_FILLCOLOR,
    TRI_FILLOPACITY,
    HM_FILLOPACITY,
    AREA_COLOR,
    AREA_WEIGHT, 
    AREA_OPACITY, 
    AREA_FILLCOLOR,
    AREA_FILLOPACITY,
}
export default common;